services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: asterra
      POSTGRES_USER: asterra_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  data-processor:
    build: ./app/data-processor
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: asterra
      DB_USER: asterra_admin
      DB_PASSWORD: password
      SQS_QUEUE_URL: http://localstack:4566/000000000000/geojson-queue
      S3_BUCKET_NAME: geojson-bucket
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localstack:4566
    depends_on:
      - postgres
      - localstack

  gdal-service:
    build: ./app/gdal-service
    ports:
      - "5000:5000"

  mapserver:
    build: ./app/mapserver
    ports:
      - "8081:80"
    environment:
      - MS_MAPFILE=/etc/mapserver/mapserver.map

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,logs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack-init:/etc/localstack/init