apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: rds-secret
  data:
    - secretKey: host
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: host
    - secretKey: port
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: port
    - secretKey: dbname
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: dbname
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: password